name: online_business
type: bigquery
connection:
  account_info_json_path: /usr/local/airflow/include/keys/de-project-creds.json
  project_id: de-project-486617
  dataset: online_business
  location: EU
